### ISSUE TITLE
QUESTION: can I use my own dataset?

### ISSUE THREAD

**Issue by NoCodeAvaible** [daandouwe/ngram-lm#1]
Hello,
I wanted to ask if someone knows if I can use my own dataset instead of the Wikitext-2 dataset.
The dataset would be build exactly like the Wikitext-2 dataset but with another language.

Thank's for every answer and suggestion in advance:)

**Comment by AliHaider20** [comment]
Yeah. I haven't gone through the code but as per the overview and the N-gram concept.
The N-gram creates words with the combination of the words.
For example if we have a word like "New York" in our dataset we know that the word is combination of both the words.

Unigram (1 gram) : This model will have words "New" and "York" separated.

Bigram (2 grams): This model will have 2 words combined so New York will be a single word in the dataset.

*Note :- The N-gram model selection depends on accurate results you get also on the dataset.

**Comment by CracKCatZ** [comment]
@AliHaider20 ok, thank you very very much:)

**Comment by AliHaider20** [comment]
Welcome. If your issue is resolved NoCodeAvailable you should close the issue.

**Comment by CracKCatZ** [comment]
Ok
